# Generated by Django 5.2.3 on 2025-06-24 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('establishments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del Plato')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Precio (Bs.)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu_items/', verbose_name='Imagen del Plato')),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='establishments.establishment', verbose_name='Establecimiento')),
                ('menu_item_types', models.ManyToManyField(blank=True, to='menu.menuitemtype', verbose_name='Tipos de Plato')),
            ],
        ),
    ]
