# Generated by Django 5.2.3 on 2025-06-24 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstablishmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='MealType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Establishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del Establecimiento')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('zone', models.CharField(blank=True, max_length=100, verbose_name='Zona')),
                ('street', models.CharField(max_length=255, verbose_name='Calle')),
                ('number', models.CharField(blank=True, max_length=20, verbose_name='Número')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitud')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitud')),
                ('establishment_types', models.ManyToManyField(to='establishments.establishmenttype', verbose_name='Tipos de Establecimiento')),
                ('meal_types', models.ManyToManyField(blank=True, to='establishments.mealtype', verbose_name='Horarios de Comida')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='establishments/', verbose_name='Imagen')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Leyenda')),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='establishments.establishment', verbose_name='Establecimiento')),
            ],
        ),
    ]
