# Generated by Django 5.2.3 on 2025-06-24 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='establishmenttype',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='mealtype',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
