# Generated by Django 5.2.3 on 2025-07-02 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishments', '0002_establishmenttype_slug_mealtype_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishment',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True, verbose_name='Latitud'),
        ),
        migrations.AlterField(
            model_name='establishment',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True, verbose_name='Longitud'),
        ),
    ]
